Repository commclassroom/classroom-monitor-bot, pull requests merged in 2021-12, with the labels that each got.

#129 fix: add more words to the list
  config.json
Labels: ⭐ goal: addition

#130 fix: add more Nitro scam definitions
  Commands/restrictedWords.js
Labels: ⭐ goal: addition

#133 fix: add remain to the whitelist
  config.json
Labels: ⭐ goal: addition, 🛠 goal: fix

#137 fix: remove unused `if` sentence
  Commands/translate.js
Labels: 💻 aspect: code

#140 fix: add `hook` to the list
  config.json
Labels: ⭐ goal: addition, 🛠 goal: fix

#145 docs: improve the `README.md` file
  README.md
Labels: 📄 aspect: text

#142 feat: Custom log and error handlers
  .gitignore
  Commands/DSA.js
  Commands/command.js
  Commands/help.js
  Commands/hey.js
  Commands/links.js
  Commands/meme.js
  Commands/presence.js
  Commands/restrictedWords.js
  Commands/source.js
  Commands/translate.js
  Commands/version.js
  index.js
  package.json
  src/Commands/DSA.js
  src/Commands/command.js
  src/Commands/help.js
  src/Commands/hey.js
  src/Commands/links.js
  src/Commands/meme.js
  src/Commands/presence.js
  src/Commands/restrictedWords.js
  src/Commands/source.js
  src/Commands/translate.js
  src/Commands/version.js
  src/utils/botErrorHandler.js
  src/utils/botLogHandler.js
Labels: 💻 aspect: code, ✨ goal: improvement

#148 fix: use `const` instead of `let`
  src/Commands/restrictedWords.js
Labels: 💻 aspect: code, ✨ goal: improvement
