Repository commclassroom/classroom-monitor-bot, pull requests merged in 2021-07, with the labels that each got.

#6 fix: :wrench: Fixed Labeling action
  .github/workflows/labels.yml
Labels: bug

#23 fix: 📝Updated Discord Link
  .github/workflows/greetings.yml
Labels: ✨ goal: improvement, 💻 aspect: code, 🔢 points: 2, 🛠 goal: fix, 🟩 priority: low

#34 [Feature] Added Bot Status
  Commands/presence.js
  index.js
Labels: Ready for merge
