Repository commclassroom/classroom-monitor-bot, pull requests merged in 2022-01, with the labels that each got.

#152 fix: Discord invitation link
  src/Commands/links.js
Labels: 🕹 aspect: interface, 🛠 goal: fix

#149 feat: restrict edtech startups
  src/Commands/restrictedWords.js
Labels: ⭐ goal: addition

#153 chore: add the `uk` word to the whitelist
  config.json
Labels: 🕹 aspect: interface, ⭐ goal: addition

#146 Build: discord v13 support, slashcommands support.
  index.js
  package.json
  src/Commands/DSA.js
  src/Commands/_COMMANDS.js
  src/Commands/help.js
  src/Commands/hey.js
  src/Commands/links.js
  src/Commands/meme.js
  src/Commands/source.js
  src/Commands/translate.js
  src/Commands/version.js
  src/config/IntentOptions.js
  src/deprecated files/command.js
  src/deprecated files/loadCommands.js
  src/deprecated files/presence.js
  src/events/onInteraction.js
  src/events/onMessage.js
  src/events/onReady.js
  src/modules/restrictedWords.js
  src/utils/validateEnv.js
Labels: 💻 aspect: code, ✨ goal: improvement
